### ISSUE TITLE
Also, it could be nice to choose a color for each event in the option (could appear in calendar and for the title of event in the list).

### ISSUE THREAD

**Issue by sergiubagrin** [ThemeFuse/Unyson-Events-Extension#7] opened 2015-03-17 09:37 UTC
Also, it could be nice to choose a color for each event in the option (could appear in calendar and for the title of event in the list).

https://github.com/ThemeFuse/Unyson/issues/363

**Comment by GheorgheP** [comment] 2015-03-23 14:39
Duplicate of #5

**Closed as completed by GheorgheP** 2015-03-23 14:39 UTC
